name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH to EC2 and Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /app
          
            if [ ! -d ".git" ]; then
              git clone https://github.com/nagul2/spring-refactor-aop-testing.git . 
            else
              git pull origin main
            fi

            ./gradlew clean build -x test

            pkill -f 'java -jar' || true
            nohup java -jar build/libs/*.jar --spring.profiles.active=dev > app.log 2>&1 &
