name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH to EC2 and Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            mkdir -p /app
            cd /app

            if [ ! -d ".git" ]; then
              git clone https://github.com/${{ github.repository }} .
            else
              git pull origin main
            fi

            # 환경변수 파일 작성
            echo "DB_ID=${{ secrets.DB_ID }}" > .env.dev
            echo "DB_PW=${{ secrets.DB_PW }}" >> .env.dev
            echo "JWT_SECRETKEY=${{ secrets.JWT_SECRETKEY }}" >> .env.dev

            # Java 설치 (필요 시)
            if ! type java > /dev/null 2>&1; then
              sudo apt update
              sudo apt install -y openjdk-17-jdk
            fi

            ./gradlew clean build -x test

            pkill -f 'java -jar' || true
            nohup java -jar build/libs/*.jar --spring.profiles.active=dev > app.log 2>&1 &
